# Generated by Django 4.2 on 2023-04-12 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rango', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaDeEntrega', models.DateField()),
                ('entregado', models.BooleanField()),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.piloto')),
            ],
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Pasajero',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='entregable',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
